backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: public/img
public_folder: img
collections:
  - name: "pages"
    label: "Pages"
    files:
    - label: "Home"
      name: "home"
      file: "content/home.md"
      fields:
        - { label: "Title", name: "title", widget: "string"}
        - { label: "Body", name: "body", widget: "markdown"}
  - name: "projects"
    label: "Projects"
    folder: "content/projects"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Hero Image", name: "thumbnail", widget: "image", required: false}
      - { label: "Title", name: "title", widget: "string"}
      - { label: "Subtitle", name: "subtitle", widget: "string"}
      - { label: "Disclaimer", name: "disclaimer", widget: "markdown", required: false}
      - label: 'Block'
        name: "block"
        widget: list
        fields:
          - label: "Paragraph"
            name: "paragraph"
            widget: "markdown"
            fields:
              - { label: "Title", name: "title", widget: "string"}
              - { label: "Body", name: "body", widget: "markdown"}
          - label: "Image"
            name: "in_text_image" 
            widget: "image"
            fields:
              - { label: "Alt Text", name: "alt", widget: "string"}
              - { label: "Caption", name: "caption", widget: "string"}
          - label: "External Link"
            name: "external_link"
            widget: "object"
            fields:
              - { label: "Title", name: "title", widget: "string"}
              - { label: "Subtitle", name: "subtitle", widget: "string"}
              - { label: "URL", name: "url", widget: "string"}